### ISSUE TITLE
Adrien's review

### ISSUE THREAD

**Issue by aallorant** [math241s24/project01-dog#3]
---
name: Adrien's review
about: Review of project proposal
title: Proposal review
---

The substance of your proposal is great.

Here are some comments about the form:

### proposal.qmd

- Make sure to include all packages:
  * the code is currently not running because `read_csv()` is not loaded (`tidyverse` required to use the `%>%` symbol for instance)
  
- The dataset should be saved in the `data` folder, which means you will have to update the path to the dataset (adding 'data/')

### about.qmd

You want to update the `About` section of your website.
  
### _quarto.yml

You want to update the `yml` document.

Specifically, you want to update the following website section of the `yml`:

```
website:
  title: Seattle Bike
  navbar:
    right:
      - icon: github
        href: https://github.com/aallorant/project01-seattle-bike
```
